[build]
  base = "."
  command = "npm install && cd frontend && npm install && npm run build"
  publish = "frontend/build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Site settings (site id will be applied when deployed)
[site]
  name = "worldexplorer-app"

# Redirect API requests to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Redirect all other routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 